package com.ethan.adatingapp.domain.enums;
/* Institution.java
Institution enum
Author: Ethan Le Roux (222622172)
Date:11 May 2025
*/
public enum Institution {
    UNIVERSITY_OF_CAPE_TOWN,
    UNIVERSITY_OF_THE_WITWATERSRAND,
    UNIVERSITY_OF_JOHANNESBURG,
    UNIVERSITY_OF_PRETORIA,
    UNIVERSITY_OF_KWAZULU_NATAL,
    STELLENBOSCH_UNIVERSITY,
    RHODES_UNIVERSITY,
    NORTH_WEST_UNIVERSITY,
    UNIVERSITY_OF_SOUTH_AFRICA,
    UNIVERSITY_OF_THE_WESTERN_CAPE,
    NELSON_MANDELA_UNIVERSITY,
    UNIVERSITY_OF_LIMPOPO,
    UNIVERSITY_OF_FORT_HARE,
    UNIVERSITY_OF_THE_FREE_STATE,
    MANGOSUTHU_UNIVERSITY_OF_TECHNOLOGY,

    CAPE_PENINSULA_UNIVERSITY_OF_TECHNOLOGY,
    DURBAN_UNIVERSITY_OF_TECHNOLOGY,
    TSHWANE_UNIVERSITY_OF_TECHNOLOGY,
    VAAL_UNIVERSITY_OF_TECHNOLOGY,

    FALSE_BAY_TVET_COLLEGE,
    NORTHLINK_COLLEGE,
    COLLEGE_OF_CAPE_TOWN,
    BOLAND_COLLEGE,
    WEST_COAST_COLLEGE,
    ELANGENI_TVET_COLLEGE,
    MAJUBA_TVET_COLLEGE,
    KING_HINTSA_TVET_COLLEGE,
    BUFFALO_CITY_TVET_COLLEGE,
    CENTRAL_JOHANNESBURG_TVET_COLLEGE,
    EKURHULENI_EAST_TVET_COLLEGE,
    SOUTH_WEST_GAUTENG_TVET_COLLEGE,
    LETABA_TVET_COLLEGE,
    MOPANI_SOUTH_EAST_TVET_COLLEGE,
    WATERBERG_TVET_COLLEGE,

    STADIO_HIGHER_EDUCATION,
    MILPARK_EDUCATION,
    VEGA_SCHOOL,
    REGENT_BUSINESS_SCHOOL,
    BOSTON_CITY_CAMPUS,
    DAMELIN_COLLEGE,
    CTI_EDUCATION_GROUP,
    EDUCOR,
    AAA_SCHOOL_OF_ADVERTISING,
    AFDA,
    INTERNATIONAL_HOTEL_SCHOOL,
    IIE_MSA,
    VARSITY_COLLEGE,
    RICHFIELD_GRADUATE_INSTITUTE,
    IMM_GRADUATE_SCHOOL,
    SAHETI_HIGHER_EDUCATION,
    LIMPOPO_ACADEMY_OF_AGRICULTURAL_ARTS;
}
